# deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: deployment-example
  namespace: myns
  labels:
    app: deployment-example-app
spec:
  # 4 Pods should exist at all times.
  replicas: 4
  selector:
    matchLabels:
      app: pod-example
  template:
    metadata:
      labels:
        app: pod-example
    spec:
      containers:
        - name: dov-bear-container
          image: chukmunnlee/dov-bear:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap-example
                  key: PORT
            - name: INSTANCE_NAME
              valueFrom:
                secretKeyRef:
                  name: secrets-example
                  key: INSTANCE_NAME
            - name: INSTANCE_HASH
              valueFrom:
                configMapKeyRef:
                  name: configmap-example
                  key: INSTANCE_HASH
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: service-example
  namespace: myns
  labels:
    app: service-example
spec:
  type: ClusterIP
  selector:
    app: pod-example
  ports:
    - port: 8080
      targetPort: 5000